version: '3'

services:
  db:
    container_name: restapi_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  app:
    container_name: restapi
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 3000:3000
