FROM node:lts-alpine

ENV DATABASE_URL="postgresql://postgres:postgres@db:5432/postgres?schema=public"

WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY ./ ./
RUN npm run generate

CMD npm run dev
