appName: restapi
appImage: ahmedaidev/restapi
appImagePolicy: IfNotPresent
appVersion: v1.0.0
appReplicas: 1
containerPort: 3000
containerEnvVars:
  - name: DATABASE_URL
    value: "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"

serviceType: ClusterIP
servicePort: 3000