appName: restapi
appImage: ahmedaidev/restapi
appImagePolicy: IfNotPresent
appVersion: 1.0.3
appReplicas: 1
containerPort: 3000
containerEnvSecrets:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: url
        key: DATABASE_URL

serviceType: ClusterIP
servicePort: 3000
