apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
          imagePullPolicy: {{ .Values.appImagePolicy }}
          env:
            {{- range .Values.containerEnvVars}}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end}}
          ports:
            - containerPort: {{ .Values.containerPort }}
          livenessProbe:
            periodSeconds: 5
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
          readinessProbe:
            periodSeconds: 5
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
          resources:
            requests:
              memory: 128Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 400m